devices: [1]
batch_size: 32
n_workers: 4
in_memory: False
val_sub: False

return_zeros: True
allow_padding: True
input_processing:
  - type: CountsPerX
    key: "gene_counts"
    factor: 10_000 
  - type: LogP1
    key: "gene_counts"



# Model args:
discrete_input: False
n_discrete_tokens: 10 # 50->9 , 100->13, 200->19, 500->29
gate_input: False
pseudoquant_input: False
dim: 256
depth: 8
dropout: 0.2
n_genes: 19331


# Pre-training args:
lr: 0.005
loss:
  type: CountMSE
  exp_output: False
  lib_norm: False
train_on_all: True
nce_loss: False
nce_dim: 64
nce_temp: 1

# Fine-tuning args:

celltype_clf_loss: False # can also be used during pre-training!
modality_prediction_loss: False

cls_finetune_dim: 134 # is used for both celltype clf loss and modality prediction finetuning
baseline_cls_task_layers: []

perturb_mode: False
baseline_perturb_dim_per_gene: 5
baseline_perturb_bottleneck_dim: 100

